name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to set up kubectl
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      # Step to configure kubeconfig
      - name: Configure kubeconfig file
        run: |
          mkdir -p $HOME/.kube
          echo "apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              certificate-authority-data: ${KUBE_CA_CERT}
              server: ${KUBE_API_SERVER}
            name: my-cluster
          contexts:
          - context:
              cluster: my-cluster
              user: my-user
              namespace: ${KUBE_NAMESPACE}
            name: my-context
          current-context: my-context
          users:
          - name: my-user
            user:
              token: ${KUBE_TOKEN}" > $HOME/.kube/config

          chmod 600 $HOME/.kube/config
        env:
          KUBE_API_SERVER: ${{ secrets.KUBE_API_SERVER }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}
          KUBE_NAMESPACE: default  # You can set this as a secret as well if needed

      # Step to test the connection
      - name: Test kubectl connection
        run: |
          kubectl cluster-info
          kubectl get nodes
