name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Create kubeconfig file
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: |
          kubectl cluster-info
